USE [Netricity]
GO

/****** Object:  Table [assets].[IISServers]    Script Date: 9-3-2017 16:38:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [assets].[IISServers](
	[Id] [smallint] IDENTITY(1,1) NOT NULL,
	[Servername] [varchar](255) NOT NULL,
 CONSTRAINT [PK_IISServers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

