USE [Netricity]
GO

/****** Object:  Table [dim].[UriQuery]    Script Date: 9-3-2017 16:36:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dim].[UriQuery](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UriQuery] [varchar](255) NOT NULL,
 CONSTRAINT [PK_UriQuery2] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

